version: 0.0
os: linux

files:
  - source: ./appspec.yml
    destination: /home/ubuntu
  - source: ./applicationStop.sh
    destination: /home/ubuntu
  - source: ./beforeInstall.sh
    destination: /home/ubuntu
  - source: ./applicationStart.sh
    destination: /home/ubuntu
  - source: ./webapp/target/csye6225.war
    destination: /var/lib/tomcat8/webapps
  - source: ./cloudWatchRestart.sh
    destination: /home/ubuntu
  - source: ./awslogs.conf
    destination: /home/ubuntu


hooks:
  ApplicationStop:
   - location: ./applicationStop.sh
     timeout: 180
     runas: ubuntu
  BeforeInstall:
   - location: ./beforeInstall.sh
     timeout: 180
     runas: ubuntu
  AfterInstall:
   - location: ./cloudWatchRestart.sh
     timeout: 360
     runas: ubuntu
  ApplicationStart:
   - location: ./applicationStart.sh
     timeout: 180
     runas: ubuntu
